PRAGMA foreign_keys = ON;

-- Upgrade the four existing advancement records into the shared subtype model.
UPDATE content_records SET
  details_json = '{"subtype":"program-group","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"K–2","officialUrl":"https://royalrangers.com/advancement/rangerkids/","contentStatus":"current","references":[{"targetId":"trail-rk-elk","targetSubtype":"achievement-trail","relationship":"begins with"},{"targetId":"trail-rk-wolverine","targetSubtype":"achievement-trail","relationship":"continues with"},{"targetId":"trail-rk-cougar","targetSubtype":"achievement-trail","relationship":"continues with"},{"targetId":"award-gold-trail","targetSubtype":"award","relationship":"culminates in"},{"targetId":"handbook-ranger-kids","targetSubtype":"handbook","relationship":"supported by"}],"accent":"#D34A36","highlights":["Three named trails provide a five-step sequence for each program year.","Ranger Kids uses its own achievement-trail structure rather than the older groups merit system.","Official curriculum and leaders remain the source for current step requirements."]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'program-ranger-kids';

UPDATE content_records SET
  details_json = '{"subtype":"program-group","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://royalrangers.com/advancement/discoveryrangers","contentStatus":"current","references":[{"targetId":"trail-discovery","targetSubtype":"achievement-trail","relationship":"follows"},{"targetId":"award-gold-eagle","targetSubtype":"award","relationship":"culminates in"},{"targetId":"handbook-discovery","targetSubtype":"handbook","relationship":"supported by"}],"accent":"#187A61","highlights":["The advancement trail uses Bible, skill, and leadership merit categories.","Blue identifies the primary skill-merit level for this Program Group.","Current official materials define every award qualification."]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'program-discovery';

UPDATE content_records SET
  details_json = '{"subtype":"program-group","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://royalrangers.com/advancement/adventurerangers","contentStatus":"current","references":[{"targetId":"trail-adventure","targetSubtype":"achievement-trail","relationship":"follows"},{"targetId":"award-adventure-gold","targetSubtype":"award","relationship":"culminates in"},{"targetId":"handbook-adventure","targetSubtype":"handbook","relationship":"supported by"}],"accent":"#1D5E91","highlights":["The advancement trail uses Bible, skill, and leadership merit categories.","Green identifies the primary skill-merit level for this Program Group.","Current official materials define every award qualification."]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'program-adventure';

UPDATE content_records SET
  details_json = '{"subtype":"program-group","programGroups":["Expedition Rangers"],"audiences":[],"gradeRange":"9–12","officialUrl":"https://royalrangers.com/advancement/expeditionrangers","contentStatus":"current","references":[{"targetId":"trail-expedition","targetSubtype":"achievement-trail","relationship":"follows"},{"targetId":"award-e3","targetSubtype":"award","relationship":"culminates in"},{"targetId":"handbook-expedition","targetSubtype":"handbook","relationship":"supported by"}],"accent":"#73528F","highlights":["The advancement trail uses advanced skill and leadership merits plus Spirit Challenge recognition.","Silver identifies the primary skill-merit level for this Program Group.","Current official materials define every award qualification."]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'program-expedition';

-- Ranger Kids sub-trails and current older-group advancement trails.
INSERT INTO content_records
  (id, kind, slug, title, summary, status, details_json, verified_at, published_at, updated_at)
VALUES
  ('trail-rk-elk', 'advancement', 'trail-to-the-elk', 'Trail to the Elk', 'The first five-step portion of the Ranger Kids three-year advancement sequence.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"K","officialUrl":"https://royalrangers.com/advancement/rangerkids/","contentStatus":"current","references":[{"targetId":"program-ranger-kids","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"trail-rk-wolverine","targetSubtype":"achievement-trail","relationship":"precedes"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-rk-wolverine', 'advancement', 'trail-to-the-wolverine', 'Trail to the Wolverine', 'The middle five-step portion of the Ranger Kids three-year advancement sequence.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"1","officialUrl":"https://royalrangers.com/advancement/rangerkids/","contentStatus":"current","references":[{"targetId":"program-ranger-kids","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"trail-rk-elk","targetSubtype":"achievement-trail","relationship":"follows"},{"targetId":"trail-rk-cougar","targetSubtype":"achievement-trail","relationship":"precedes"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-rk-cougar', 'advancement', 'trail-to-the-cougar', 'Trail to the Cougar', 'The final five-step portion of the Ranger Kids three-year advancement sequence.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"2","officialUrl":"https://royalrangers.com/advancement/rangerkids/","contentStatus":"current","references":[{"targetId":"program-ranger-kids","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"trail-rk-wolverine","targetSubtype":"achievement-trail","relationship":"follows"},{"targetId":"award-gold-trail","targetSubtype":"award","relationship":"leads toward"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-discovery', 'advancement', 'discovery-rangers-advancement-trail', 'Discovery Rangers Advancement Trail', 'A grade 3–5 advancement structure that brings together Bible, skill, and leadership merit categories.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://royalrangers.com/advancement/discoveryrangers","contentStatus":"current","references":[{"targetId":"program-discovery","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"award-gold-eagle","targetSubtype":"award","relationship":"culminates in"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-adventure', 'advancement', 'adventure-rangers-advancement-trail', 'Adventure Rangers Advancement Trail', 'A grade 6–8 advancement structure that develops Bible, skill, and leadership learning at the Adventure level.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://royalrangers.com/advancement/adventurerangers","contentStatus":"current","references":[{"targetId":"program-adventure","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"award-adventure-gold","targetSubtype":"award","relationship":"culminates in"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-expedition', 'advancement', 'expedition-rangers-advancement-trail', 'Expedition Rangers Advancement Trail', 'A grade 9–12 advancement structure combining advanced skills, leadership development, and Spirit Challenge recognition.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Expedition Rangers"],"audiences":[],"gradeRange":"9–12","officialUrl":"https://royalrangers.com/advancement/expeditionrangers","contentStatus":"current","references":[{"targetId":"program-expedition","targetSubtype":"program-group","relationship":"belongs to"},{"targetId":"award-e3","targetSubtype":"award","relationship":"culminates in"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('trail-fcf-grizzly', 'advancement', 'trail-of-the-grizzly', 'Trail of the Grizzly', 'The FCF advancement overview progresses through three named membership statuses for eligible boys and adult leaders.', 'published',
   '{"subtype":"achievement-trail","programGroups":["Adventure Rangers","Expedition Rangers"],"audiences":["FCF","Leaders"],"gradeRange":null,"officialUrl":"https://royalrangers.com/fcf","contentStatus":"current","references":[{"targetId":"handbook-fcf","targetSubtype":"handbook","relationship":"documented by"}]}',
   '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z');

-- A representative title set plus category/color records. Titles only; no requirements or worksheets are copied.
INSERT INTO content_records
  (id, kind, slug, title, summary, status, details_json, verified_at, published_at, updated_at)
VALUES
  ('merit-blue-art', 'advancement', 'blue-art-merit', 'Art', 'A publicly indexed introductory skill-merit title; use the official blue merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=67FD11862B104E4FB78076BAAC0332DE&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["blue"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-blue-astronomy', 'advancement', 'blue-astronomy-merit', 'Astronomy', 'A publicly indexed introductory skill-merit title; use the official blue merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=67FD11862B104E4FB78076BAAC0332DE&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["blue"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-blue-cooking', 'advancement', 'blue-cooking-merit', 'Cooking', 'A publicly indexed introductory skill-merit title; use the official blue merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=67FD11862B104E4FB78076BAAC0332DE&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["blue"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-blue-first-aid', 'advancement', 'blue-first-aid-skills-merit', 'First Aid Skills', 'A publicly indexed introductory skill-merit title; use the official blue merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=67FD11862B104E4FB78076BAAC0332DE&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["blue"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-green-archery', 'advancement', 'green-archery-merit', 'Archery', 'A publicly indexed intermediate skill-merit title; use the official green merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=542F6ACF15C744B598D4E2FE8A331E75&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["green"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-green-camping', 'advancement', 'green-camping-merit', 'Camping', 'A publicly indexed intermediate skill-merit title; use the official green merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=542F6ACF15C744B598D4E2FE8A331E75&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["green"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-green-computers', 'advancement', 'green-computers-merit', 'Computers', 'A publicly indexed intermediate skill-merit title; use the official green merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=542F6ACF15C744B598D4E2FE8A331E75&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["green"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-green-photography', 'advancement', 'green-photography-merit', 'Photography', 'A publicly indexed intermediate skill-merit title; use the official green merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=542F6ACF15C744B598D4E2FE8A331E75&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["green"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-silver-auto-mechanics', 'advancement', 'silver-auto-mechanics-merit', 'Auto Mechanics', 'A publicly indexed advanced skill-merit title; use the official silver merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=8AC2DF6BA0A54F99981FB6BCFFF29D68&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["silver"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-silver-budget-finance', 'advancement', 'silver-budget-finance-merit', 'Budget & Finance', 'A publicly indexed advanced skill-merit title; use the official silver merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=8AC2DF6BA0A54F99981FB6BCFFF29D68&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["silver"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-silver-public-health', 'advancement', 'silver-public-health-merit', 'Public Health', 'A publicly indexed advanced skill-merit title; use the official silver merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=8AC2DF6BA0A54F99981FB6BCFFF29D68&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["silver"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-silver-wilderness-survival', 'advancement', 'silver-wilderness-survival-merit', 'Wilderness Survival', 'A publicly indexed advanced skill-merit title; use the official silver merit index for current requirements.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/~/link.aspx?_id=8AC2DF6BA0A54F99981FB6BCFFF29D68&_z=z","contentStatus":"current","references":[],"meritCategory":"skill","colors":["silver"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-discovery-bible', 'advancement', 'discovery-bible-merits', 'Discovery Rangers Bible Merits', 'The Discovery Rangers Bible-merit category is identified by orange; lesson content remains in current official materials.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://royalrangers.com/merits","contentStatus":"current","references":[{"targetId":"trail-discovery","targetSubtype":"achievement-trail","relationship":"supports"}],"meritCategory":"bible","colors":["orange"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-adventure-bible', 'advancement', 'adventure-bible-merits', 'Adventure Rangers Bible Merits', 'The Adventure Rangers Bible-merit category is identified by brown; lesson content remains in current official materials.', 'published', '{"subtype":"merit","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://royalrangers.com/merits","contentStatus":"current","references":[{"targetId":"trail-adventure","targetSubtype":"achievement-trail","relationship":"supports"}],"meritCategory":"bible","colors":["brown"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-discovery-leadership', 'advancement', 'discovery-leadership-merits', 'Discovery Rangers Leadership Merits', 'The Discovery Rangers leadership-merit category is identified by red; lesson sets remain in current official materials.', 'published', '{"subtype":"merit","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://royalrangers.com/merits","contentStatus":"current","references":[{"targetId":"trail-discovery","targetSubtype":"achievement-trail","relationship":"supports"}],"meritCategory":"leadership","colors":["red"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-adventure-leadership', 'advancement', 'adventure-leadership-merits', 'Adventure Rangers Leadership Merits', 'The Adventure Rangers leadership-merit category is identified by gold; lesson sets remain in current official materials.', 'published', '{"subtype":"merit","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://royalrangers.com/merits","contentStatus":"current","references":[{"targetId":"trail-adventure","targetSubtype":"achievement-trail","relationship":"supports"}],"meritCategory":"leadership","colors":["gold"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('merit-expedition-leadership', 'advancement', 'expedition-leadership-merits', 'Expedition Rangers Leadership Merits', 'The Expedition Rangers leadership-merit category is identified by sky blue; lesson sets remain in current official materials.', 'published', '{"subtype":"merit","programGroups":["Expedition Rangers"],"audiences":[],"gradeRange":"9–12","officialUrl":"https://royalrangers.com/merits","contentStatus":"current","references":[{"targetId":"trail-expedition","targetSubtype":"achievement-trail","relationship":"supports"}],"meritCategory":"leadership","colors":["sky-blue"]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z');

-- Structured award overviews; exact qualifications remain at the official pages.
INSERT INTO content_records
  (id, kind, slug, title, summary, status, details_json, verified_at, published_at, updated_at)
VALUES
  ('award-gold-trail', 'advancement', 'gold-trail-award', 'Gold Trail Award', 'The highest age-group recognition named on the current Ranger Kids advancement page.', 'published', '{"subtype":"award","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"K–2","officialUrl":"https://royalrangers.com/advancement/rangerkids/","contentStatus":"current","references":[{"targetId":"trail-rk-cougar","targetSubtype":"achievement-trail","relationship":"follows the Ranger Kids sequence"}],"awardLevel":"program-group"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('award-gold-eagle', 'advancement', 'gold-eagle-award', 'Gold Eagle Award', 'The highest age-group recognition named on the current Discovery Rangers advancement page.', 'published', '{"subtype":"award","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://royalrangers.com/advancement/discoveryrangers","contentStatus":"current","references":[{"targetId":"trail-discovery","targetSubtype":"achievement-trail","relationship":"belongs to"}],"awardLevel":"program-group"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('award-adventure-gold', 'advancement', 'adventure-gold-award', 'Adventure Gold Award', 'The highest age-group recognition named on the current Adventure Rangers advancement page.', 'published', '{"subtype":"award","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://royalrangers.com/advancement/adventurerangers","contentStatus":"current","references":[{"targetId":"trail-adventure","targetSubtype":"achievement-trail","relationship":"belongs to"}],"awardLevel":"program-group"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('award-e3', 'advancement', 'e3-award', 'E3 Award', 'The highest age-group recognition named on the current Expedition Rangers advancement page.', 'published', '{"subtype":"award","programGroups":["Expedition Rangers"],"audiences":[],"gradeRange":"9–12","officialUrl":"https://royalrangers.com/advancement/expeditionrangers","contentStatus":"current","references":[{"targetId":"trail-expedition","targetSubtype":"achievement-trail","relationship":"belongs to"}],"awardLevel":"program-group"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('award-trail-saber', 'advancement', 'trail-of-the-saber', 'Trail of the Saber', 'A junior-leadership recognition for sustained development across the older Program Groups; current details and application steps remain at the national source.', 'published', '{"subtype":"award","programGroups":["Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/training/junior/tots","contentStatus":"current","references":[{"targetId":"merit-discovery-leadership","targetSubtype":"merit","relationship":"relates to junior leadership development"},{"targetId":"merit-adventure-leadership","targetSubtype":"merit","relationship":"relates to junior leadership development"},{"targetId":"merit-expedition-leadership","targetSubtype":"merit","relationship":"relates to junior leadership development"}],"awardLevel":"junior-leadership"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('award-gma', 'advancement', 'gold-medal-of-achievement', 'Gold Medal of Achievement', 'Royal Rangers USA identifies the GMA as its highest achievement award for boys, reflecting sustained advancement, Bible engagement, outpost participation, and service.', 'published', '{"subtype":"award","programGroups":["Ranger Kids","Discovery Rangers","Adventure Rangers","Expedition Rangers"],"audiences":[],"gradeRange":null,"officialUrl":"https://royalrangers.com/gma","contentStatus":"current","references":[{"targetId":"award-gold-trail","targetSubtype":"award","relationship":"recognized in further distinctions"},{"targetId":"award-gold-eagle","targetSubtype":"award","relationship":"age-group recognition"},{"targetId":"award-adventure-gold","targetSubtype":"award","relationship":"age-group recognition"},{"targetId":"award-e3","targetSubtype":"award","relationship":"age-group recognition"}],"awardLevel":"national"}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z');

-- Publisher listings only. No book files, retailer assets, or protected excerpts are stored.
INSERT INTO content_records
  (id, kind, slug, title, summary, status, details_json, verified_at, published_at, updated_at)
VALUES
  ('handbook-ranger-kids', 'advancement', 'ranger-kids-handbook', 'Ranger Kids Handbook', 'A publisher-listed handbook for Ranger Kids participants; the listing points to authorized print and e-book purchase options.', 'published', '{"subtype":"handbook","programGroups":["Ranger Kids"],"audiences":[],"gradeRange":"K–2","officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=022115","contentStatus":"current","references":[{"targetId":"program-ranger-kids","targetSubtype":"program-group","relationship":"serves"}],"publisher":"Gospel Publishing House","itemNumber":"022115","edition":null,"revision":null,"publicationYear":null,"availability":"available","formats":["print","ebook"],"purchaseUrls":[{"label":"Publisher print listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=022115"},{"label":"Publisher e-book retailer links","format":"ebook","url":"https://myhealthychurch.com/store/startitem.cfm?item=022115"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('handbook-discovery', 'advancement', 'discovery-rangers-handbook', 'Discovery Rangers Handbook', 'A publisher-listed handbook for Discovery Rangers participants; the listing points to authorized print and e-book purchase options.', 'published', '{"subtype":"handbook","programGroups":["Discovery Rangers"],"audiences":[],"gradeRange":"3–5","officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=020615","contentStatus":"current","references":[{"targetId":"program-discovery","targetSubtype":"program-group","relationship":"serves"}],"publisher":"Gospel Publishing House","itemNumber":"020615","edition":null,"revision":null,"publicationYear":null,"availability":"available","formats":["print","ebook"],"purchaseUrls":[{"label":"Publisher print listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=020615"},{"label":"Publisher e-book retailer links","format":"ebook","url":"https://myhealthychurch.com/store/startitem.cfm?item=020615"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('handbook-adventure', 'advancement', 'adventure-rangers-handbook', 'Adventure Rangers Handbook', 'A publisher-listed handbook for Adventure Rangers participants; the listing points to authorized print and e-book purchase options.', 'published', '{"subtype":"handbook","programGroups":["Adventure Rangers"],"audiences":[],"gradeRange":"6–8","officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=020616","contentStatus":"current","references":[{"targetId":"program-adventure","targetSubtype":"program-group","relationship":"serves"}],"publisher":"Gospel Publishing House","itemNumber":"020616","edition":null,"revision":null,"publicationYear":null,"availability":"available","formats":["print","ebook"],"purchaseUrls":[{"label":"Publisher print listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=020616"},{"label":"Publisher e-book retailer links","format":"ebook","url":"https://myhealthychurch.com/store/startitem.cfm?item=020616"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('handbook-expedition', 'advancement', 'expedition-rangers-handbook', 'Expedition Rangers Handbook', 'A publisher-listed handbook for Expedition Rangers participants; the listing points to authorized print and e-book purchase options.', 'published', '{"subtype":"handbook","programGroups":["Expedition Rangers"],"audiences":[],"gradeRange":"9–12","officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=020617","contentStatus":"current","references":[{"targetId":"program-expedition","targetSubtype":"program-group","relationship":"serves"}],"publisher":"Gospel Publishing House","itemNumber":"020617","edition":null,"revision":null,"publicationYear":null,"availability":"available","formats":["print","ebook"],"purchaseUrls":[{"label":"Publisher print listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=020617"},{"label":"Publisher e-book retailer links","format":"ebook","url":"https://myhealthychurch.com/store/startitem.cfm?item=020617"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('handbook-leader-manual', 'advancement', 'royal-rangers-leader-manual', 'Royal Rangers Leader Manual', 'A publisher-listed text-only leader resource currently verified as a three-hole-punched loose-leaf print product; digital availability is not verified.', 'published', '{"subtype":"handbook","programGroups":[],"audiences":["Leaders"],"gradeRange":null,"officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=022171","contentStatus":"current","references":[],"publisher":"Gospel Publishing House","itemNumber":"022171","edition":null,"revision":null,"publicationYear":null,"availability":"available","formats":["print"],"purchaseUrls":[{"label":"Publisher print listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=022171"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z'),
  ('handbook-fcf', 'advancement', 'frontiersmen-camping-fellowship-handbook', 'Frontiersmen Camping Fellowship Handbook', 'The publisher listing identifies this 2021 paperback as the FCF reference handbook; digital availability is not verified.', 'published', '{"subtype":"handbook","programGroups":["Adventure Rangers","Expedition Rangers"],"audiences":["FCF","Leaders"],"gradeRange":null,"officialUrl":"https://myhealthychurch.com/store/startitem.cfm?item=020540","contentStatus":"current","references":[{"targetId":"trail-fcf-grizzly","targetSubtype":"achievement-trail","relationship":"documents"}],"publisher":"Gospel Publishing House","itemNumber":"020540","edition":"2021 Edition","revision":null,"publicationYear":2021,"availability":"available","formats":["print"],"purchaseUrls":[{"label":"Publisher paperback listing","format":"print","url":"https://myhealthychurch.com/store/startitem.cfm?item=020540"}]}', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z', '2026-08-12T00:00:00.000Z');

-- Replace contradictory legacy landing copy with concise links into the structured library.
UPDATE content_records SET
  title = 'Trail of the Saber and GMA',
  summary = 'A concise landing page for the structured Trail of the Saber and Gold Medal of Achievement records.',
  details_json = '{"section":"other","body":["Trail of the Saber is a junior-leadership recognition, while the Gold Medal of Achievement is identified by Royal Rangers USA as its highest achievement award for boys.","The Advancement Library holds the source-backed award summaries. Current official pages and leaders remain the source for qualifications, applications, and award decisions."],"links":[{"label":"Open the Advancement Library","url":"/advancement"},{"label":"Official Trail of the Saber page","url":"https://royalrangers.com/training/junior/tots"},{"label":"Official GMA information","url":"https://royalrangers.com/gma"}]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'page-trail-gma';

UPDATE content_records SET
  title = 'Uniforms and the Ideals of Royal Rangers',
  summary = 'Current official links with original context for uniform choices and the Ideals of Royal Rangers.',
  details_json = '{"section":"other","body":["Royal Rangers USA describes four uniform approaches and gives local outposts flexibility to select an option appropriate to their church and community. Current official guidance should be checked before buying or placing insignia.","The Ideals of Royal Rangers bring together its pledge, character code, readiness motto, Golden Rule, and emblem symbolism. This independent site summarizes their role without reproducing the official wording or artwork."],"links":[{"label":"Official uniform information","url":"https://royalrangers.com/uniforms"},{"label":"Official About Us and Ideals page","url":"https://royalrangers.com/about"}]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'page-uniforms-pledges';

UPDATE content_records SET
  summary = 'An introduction to FCF, its Trail of the Grizzly overview, and its separate handbook listing.',
  details_json = '{"section":"other","body":["Frontiersmen Camping Fellowship is a Royal Rangers program for men and boys centered on frontier-era outdoor skills, fellowship, personal development, and service.","Its Trail of the Grizzly and handbook are represented as structured Advancement Library records. An outpost FCF Activity Status remains a separate three-state fact and is never inferred from this national overview."],"links":[{"label":"Open the Advancement Library","url":"/advancement"},{"label":"Official FCF page","url":"https://royalrangers.com/fcf"}]}',
  verified_at = '2026-08-12T00:00:00.000Z', updated_at = '2026-08-12T00:00:00.000Z'
WHERE id = 'page-fcf';

-- Refresh and add visible primary-source provenance.
UPDATE record_sources SET
  label = 'Royal Rangers USA advancement page',
  url = json_extract((SELECT details_json FROM content_records WHERE content_records.id = record_sources.record_id), '$.officialUrl'),
  verified_at = '2026-08-12T00:00:00.000Z'
WHERE record_id IN ('program-ranger-kids', 'program-discovery', 'program-adventure', 'program-expedition');

DELETE FROM record_sources WHERE record_id IN ('page-trail-gma', 'page-uniforms-pledges', 'page-fcf');
INSERT INTO record_sources (id, record_id, field_name, label, url, verified_at) VALUES
  ('source-page-trail-saber', 'page-trail-gma', 'record', 'Royal Rangers USA Trail of the Saber', 'https://royalrangers.com/training/junior/tots', '2026-08-12T00:00:00.000Z'),
  ('source-page-gma', 'page-trail-gma', 'record', 'Royal Rangers USA Gold Medal of Achievement', 'https://royalrangers.com/gma', '2026-08-12T00:00:00.000Z'),
  ('source-page-uniforms', 'page-uniforms-pledges', 'record', 'Royal Rangers USA Uniforms', 'https://royalrangers.com/uniforms', '2026-08-12T00:00:00.000Z'),
  ('source-page-ideals', 'page-uniforms-pledges', 'record', 'Royal Rangers USA About Us', 'https://royalrangers.com/about', '2026-08-12T00:00:00.000Z'),
  ('source-page-fcf-current', 'page-fcf', 'record', 'Royal Rangers USA FCF', 'https://royalrangers.com/fcf', '2026-08-12T00:00:00.000Z');

INSERT INTO record_sources (id, record_id, field_name, label, url, verified_at)
SELECT
  'source-' || id || '-advancement-library',
  id,
  'record',
  CASE
    WHEN json_extract(details_json, '$.subtype') = 'handbook' THEN 'Gospel Publishing House product listing'
    WHEN json_extract(details_json, '$.subtype') = 'merit' THEN 'Royal Rangers USA merit index'
    WHEN id = 'trail-fcf-grizzly' THEN 'Royal Rangers USA FCF'
    WHEN id = 'award-trail-saber' THEN 'Royal Rangers USA Trail of the Saber'
    WHEN id = 'award-gma' THEN 'Royal Rangers USA Gold Medal of Achievement'
    ELSE 'Royal Rangers USA advancement page'
  END,
  json_extract(details_json, '$.officialUrl'),
  '2026-08-12T00:00:00.000Z'
FROM content_records
WHERE kind = 'advancement'
  AND id NOT IN ('program-ranger-kids', 'program-discovery', 'program-adventure', 'program-expedition');

INSERT INTO audit_events (record_id, action, actor, after_json, reason, created_at)
SELECT id, 'advancement library seeded', 'MVP seed', details_json,
  'Slice 2 source-backed advancement and handbook library', '2026-08-12T00:00:00.000Z'
FROM content_records
WHERE kind = 'advancement' OR id IN ('page-trail-gma', 'page-uniforms-pledges', 'page-fcf');
