import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { cancelWorkspaceCalendarEntry, createWorkspaceCalendarEntry, fetchWorkspace, fetchWorkspaceCalendar, setWorkspaceTimezone, updateWorkspaceCalendarEntry, type WorkspaceCalendarEntry, type WorkspaceSummary } from '../data/client'

const today = () => new Date().toISOString().slice(0,10)
const plusDays = (value:string, days:number) => new Date(Date.parse(`${value}T00:00:00Z`)+days*86400000).toISOString().slice(0,10)

export function OutpostWorkspacePage() {
  const [summary,setSummary]=useState<WorkspaceSummary|null>(null), [entries,setEntries]=useState<WorkspaceCalendarEntry[]>([])
  const [error,setError]=useState(''), [loading,setLoading]=useState(true), [editing,setEditing]=useState<WorkspaceCalendarEntry|null>(null)
  const [from,setFrom]=useState(today()), [to,setTo]=useState(plusDays(today(),60))
  const load=useCallback(async()=>{setLoading(true);setError('');try{const {data}=await fetchWorkspace();setSummary(data);if(data.workspace){setEntries((await fetchWorkspaceCalendar(from,to)).data.items)}}catch(reason){setError(reason instanceof Error?reason.message:'Workspace unavailable.')}finally{setLoading(false)}},[from,to])
  useEffect(()=>{void load()},[load])
  if(loading) return <section className="workspace-page wrap narrow" aria-busy="true"><h1>Outpost Workspace</h1><p role="status">Loading your private group calendar…</p></section>
  if(error&&!summary) return <section className="workspace-page wrap narrow"><h1>Outpost Workspace</h1><div className="form-error" role="alert">{error}</div><p>Sign in with an active verified Membership for this exact Outpost.</p><a href="/account">Open Account</a></section>
  const workspace=summary?.workspace
  const saveTimezone=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const value=new FormData(event.currentTarget).get('timeZone') as string;try{setSummary((await setWorkspaceTimezone(value,workspace?.version??null)).data);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Timezone could not be saved.')}}
  const saveEntry=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const allDay=form.get('allDay')==='on';const payload={title:form.get('title'),description:form.get('description')||null,category:form.get('category'),startDate:form.get('startDate'),endDate:form.get('endDate'),startTime:allDay?null:form.get('startTime')||null,endTime:allDay?null:form.get('endTime')||null,allDay,location:form.get('location')||null,status:form.get('status'),requestKey:editing?`edit-${editing.id}`:crypto.randomUUID()};try{if(editing)await updateWorkspaceCalendarEntry(editing.id,payload,editing.version);else await createWorkspaceCalendarEntry(payload);setEditing(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Entry could not be saved.')}}
  return <section className="workspace-page wrap"><p className="eyebrow">Private Outpost collaboration</p><h1>Outpost Workspace</h1><p>This calendar records the Outpost’s group plans. It is not a roster, RSVP, attendance, or youth-progress tool.</p>{error&&<div className="form-error" role="alert">{error}</div>}
    {!workspace&&summary?.canManage&&<form className="account-panel form-stack" onSubmit={saveTimezone}><h2>Choose the Outpost timezone</h2><p>Choose explicitly; the hub will not guess from location or your browser.</p><label>IANA timezone<input name="timeZone" placeholder="America/New_York" required /></label><button>Start workspace</button></form>}
    {workspace&&<><div className="workspace-toolbar"><strong>Timezone: {workspace.timeZone}</strong><span>Status: {workspace.state}</span></div>{summary?.canManage&&workspace.state==='active'&&<details className="account-panel"><summary>{editing?'Edit group plan':'Create a group plan'}</summary><form className="form-stack" onSubmit={saveEntry}><p className="privacy-warning"><strong>Keep private personal data out.</strong> Do not enter youth/member names, rosters, contact or medical details, transportation lists, or private residences.</p><label>Title<input name="title" maxLength={120} defaultValue={editing?.title} required /></label><label>Description<textarea name="description" maxLength={1000} defaultValue={editing?.description??''} /></label><label>Category<select name="category" defaultValue={editing?.category??'meeting'}>{['meeting','camp','service','training','ceremony','fundraiser','other'].map(x=><option key={x}>{x}</option>)}</select></label><div className="workspace-dates"><label>Start date<input name="startDate" type="date" defaultValue={editing?.startDate??from} required /></label><label>End date<input name="endDate" type="date" defaultValue={editing?.endDate??from} required /></label></div><label className="check-row"><input name="allDay" type="checkbox" defaultChecked={editing?Boolean(editing.allDay):true} />All-day plan</label><div className="workspace-dates"><label>Start time<input name="startTime" type="time" defaultValue={editing?.startTime??''} /></label><label>End time<input name="endTime" type="time" defaultValue={editing?.endTime??''} /></label></div><label>General venue<input name="location" maxLength={200} defaultValue={editing?.location??''} /></label><label>Group-plan status<select name="status" defaultValue={editing?.status??'planned'}>{['tentative','planned','confirmed','completed'].map(x=><option key={x}>{x}</option>)}</select></label><div className="account-actions"><button>{editing?'Save changes':'Create entry'}</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancel edit</button>}</div></form></details>}
      <div className="workspace-range"><label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>To <input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label></div><h2>Upcoming agenda</h2>{entries.length===0?<p>No group plans in this range.</p>:<ol className="workspace-agenda">{entries.map(entry=><li key={entry.id}><article><p><time dateTime={entry.startDate}>{entry.startDate}</time>{entry.startTime&&` at ${entry.startTime}`} · {entry.timeZone}</p><h3>{entry.title}</h3><p>{entry.category} · <strong>{entry.status}</strong>{entry.location&&` · ${entry.location}`}</p>{entry.description&&<p>{entry.description}</p>}{summary?.canManage&&workspace.state==='active'&&entry.status!=='cancelled'&&<div className="account-actions"><button onClick={()=>setEditing(entry)}>Edit</button><button onClick={async()=>{try{await cancelWorkspaceCalendarEntry(entry.id,entry.version);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Entry changed.')}}}>Cancel entry</button></div>}</article></li>)}</ol>}
      {summary?.canManage&&<form className="timezone-change form-stack" onSubmit={saveTimezone}><label>Change timezone<input name="timeZone" defaultValue={workspace.timeZone} required /></label><button disabled={workspace.state==='read-only'}>Save timezone</button></form>}</>}
    <nav className="workspace-links" aria-label="Related pages"><a href="/outposts">Public Outpost</a><a href="/advancement">Advancement</a><a href="/events">Reference Events</a><a href="/help">Help</a></nav></section>
}
